name: Jekyll Project Build & Deploy
description: 'Builds & deploys a Jekyll 4.x site to master branch of the same repository.'
branding:
  icon: 'package'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
